version: '3.8'
services:
  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: client_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuenta_movimientos
    ports:
      - "3308:3306"
    volumes:
      - mysql2-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management console
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  client-person:
    build:
      context: ./client-person
      dockerfile: Dockerfile
    container_name: client-person
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres_db;Port=5432;Database=client_db;Username=postgres;Password=postgres
      RabbitMQ__Host: rabbitmq
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__RequestQueue: cliente_request_queue
      RabbitMQ__ResponseQueue: cliente_response_queue
      RabbitMQ__ResponseExchange: cliente_response_exchange
      RabbitMQ__ResponseRoutingKey: cliente_response_routing_key
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_db:
        condition: service_started

  microservicio-cuenta-movimientos:
    build:
      context: ./microservicio-cuenta-movimientos
      dockerfile: Dockerfile
    container_name: microservicio-cuenta-movimientos
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql2:3306/cuenta_movimientos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - mysql2
      - rabbitmq

volumes:
  pgdata1:
  mysql2-data:
